server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: wiki5620
logging:
  level:
    top:
      siki:
        mybatis: trace